---
- name: Depopulate Tower Objects
  hosts: localhost
  gather_facts: false

  collections:
    - ansible.tower

  vars_files:
    - files/vars.yml
    - files/users.yml
  vars:
    inventory: "Satellite"

  tasks:

  # delete workflow
    - name: Remove workflow template
      tower_workflow_job_template:
        name: "00 RHEL Pipeline"
        organization: "Default"
        state: absent

  # delete job templates
    - name: Remove job templates
      tower_job_template:
        name: "{{ item }}"
        state: absent
      loop:
        - "01 RHEL Raw Setup"
        - "02 SSH Hardening"
        - "03 Attach to Satellite"
        - "04 Deploy HTTPD"
        - "05 Deploy MSSQL"

  # delete inventory
    - name: Remove main inventory
      tower_inventory:
        name: "{{ inventory }}"
        organization: "Default"
        state: absent

  # delete projects
    - name: Remove main project
      tower_project:
        name: "{{ project }}"
        organization: "Default"
        state: absent

  # delete credentials
    - name: Remove credentials
      tower_credential:  
        name: "{{ item.name }}"
        organization: "Default"
        credential_type: "{{ item.type }}"
        state: absent
      loop:
        - { name: "{{ git_creds }}", type: 'Source Control' }
        - { name: "{{ satellite_creds }}", type: 'Red Hat Satellite 6' }
        - { name: "{{ machine_creds }}", type: 'Machine' }
        - { name: "{{ machine_key_creds }}", type: 'Machine' }
 
  # delete users and teams
    - name: Remove users
      tower_user:
        username: "{{ item.username }}"
        state: absent
      loop: "{{ users }}"

    - name: Remove Jr Ops team
      tower_team:
        name: "Jr Ops"
        description: "Junior Operations"
        organization: "Default"
        state: absent
    
