= Ansible Tower Demo

This is a pre-canned demo for an existing tower installation. You need AWX CLI and the associated configurations for it, plus the tower_cli.cfg file for login. See https://galaxy.ansible.com/awx/awx for details on setup.

== Requirements
* awx-cli - an example environment script is provided in the files folder, run with `. awx-cli-env.sh`
* vault.yml filling in the variables in the vault-template.yml
* users.yml based on users-template.yml
* The playbooks here: https://github.com/CorwinBurton/tower-demos.git
* Working Tower or AWX install
* Either the ansible.tower collection or the awx.awx collection
** If you use the awx.awx, you need to swap out the collection at the top of the playbooks

=== Collections
* requirements.yml contains the required collections, ensure that you have access to the Automation Hub

.Example .ansible.cfg
-----
...

[galaxy]
server_list = automation_hub, galaxy

[galaxy_server.automation_hub]
url=https://console.redhat.com/api/automation-hub/
auth_url=https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
token= # get the token from https://console.redhat.com/ansible/automation-hub/token

[galaxy_server.galaxy]
url=https://galaxy.ansible.com/

...
-----