collections:
  - name: ansible.tower
    #version: 3.8.3
    source: https://console.redhat.com/api/automation-hub/

  - name: ansible.controller
    #version: 4.0.0
    source: https://console.redhat.com/api/automation-hub/

  - name: awx.awx
